name: Terraform Flask App to ECS

on:
  workflow_dispatch: # Allows manual trigger of the workflow
    inputs:
      mode:
        description: 'Choose operation mode'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy
      confirm_destroy:
        description: 'Type "delete" to proceed with destroy'
        required: false
        default: ''

permissions: # Workflow-level permissions
  contents: write
  id-token: write
          
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Run Terraform in ${{ github.event.inputs.mode }} mode

    #env:
      #ACTIONS_STEP_DEBUG: true

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print branch name
        run: |
          echo "Running on branch: ${{ github.ref_name }}"
        
      # Step 2: Set up Python and install boto3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install boto3
        run: pip install boto3

      # Step 3: install AWS CLI in the workflow
      #- name: Install AWS CLI
      #  run: sudo apt-get update && sudo apt-get install -y awscli

      # Step 4: Configure AWS credentials using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::266735837076:role/githubactions_aws_credentials_role
          aws-region: us-west-2

      # Step 5: verify credentials are loaded correctly
      - name: Test AWS Access
        run: aws sts get-caller-identity

      # Step 6: Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Determine Backend Config
        id: backend-config
        run: |
          if [ "${{ github.ref_name }}" == "master" ]; then
            echo "::set-output name=state_file::master/terraform.tfstate"
            echo "::set-output name=lock_table::terraform_locks_table_master"
          else
            echo "::set-output name=state_file::ec2-branch/terraform.tfstate"
            echo "::set-output name=lock_table::terraform_locks_table_ec2_branch"
          fi

      - name: Print Backend Config
        run: |
          echo "State File: ${{ steps.backend-config.outputs.state_file }}"
          echo "Lock Table: ${{ steps.backend-config.outputs.lock_table }}"

      # Step 7: Terraform Init
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=terraform-state-bucket-266735837076" \
            -backend-config="key=${{ steps.backend-config.outputs.state_file }}" \
            -backend-config="region=us-west-2" \
            -backend-config="dynamodb_table=${{ steps.backend-config.outputs.lock_table }}" \

      - name: Create ECR Repository if Not Exists (flask-app)
        if: ${{ github.event.inputs.mode != 'destroy' }}
        run: |
          aws ecr describe-repositories --repository-names flask-app --region us-west-2 || \
          aws ecr create-repository --repository-name flask-app --region us-west-2

      - name: Create ECR Repository if Not Exists (genai-service)
        if: ${{ github.event.inputs.mode != 'destroy' }}
        run: |
          aws ecr describe-repositories --repository-names genai-service --region us-west-2 || \
          aws ecr create-repository --repository-name genai-service --region us-west-2

      - name: Create ECR Repository if Not Exists (sentiment-service)
        if: ${{ github.event.inputs.mode != 'destroy' }}
        run: |
          aws ecr describe-repositories --repository-names sentiment-service --region us-west-2 || \
          aws ecr create-repository --repository-name sentiment-service --region us-west-2

      - name: Create ECR Repository if Not Exists (dynamodb-service)
        if: ${{ github.event.inputs.mode != 'destroy' }}
        run: |
          aws ecr describe-repositories --repository-names dynamodb-service --region us-west-2 || \
          aws ecr create-repository --repository-name dynamodb-service --region us-west-2

      - name: Login to Amazon ECR
        if: ${{ github.event.inputs.mode != 'destroy' }}
        run: |
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 266735837076.dkr.ecr.us-west-2.amazonaws.com

      - name: Build and Push Docker Image (flask-app)
        if: ${{ github.event.inputs.mode != 'destroy' }}
        run: |
          docker build -t flask-app .
          docker tag flask-app:latest 266735837076.dkr.ecr.us-west-2.amazonaws.com/flask-app:latest
          docker push 266735837076.dkr.ecr.us-west-2.amazonaws.com/flask-app:latest    

      - name: Build and Push Docker Image (genai-repo)
        if: ${{ github.event.inputs.mode != 'destroy' }}
        run: |
          docker build -t genai-service .
          docker tag genai-service:latest 266735837076.dkr.ecr.us-west-2.amazonaws.com/genai-service:latest
          docker push 266735837076.dkr.ecr.us-west-2.amazonaws.com/genai-service:latest

      - name: Build and Push Docker Image (sentiment-repo)
        if: ${{ github.event.inputs.mode != 'destroy' }}
        run: |
          docker build -t sentiment-service .
          docker tag sentiment-service:latest 266735837076.dkr.ecr.us-west-2.amazonaws.com/sentiment-service:latest
          docker push 266735837076.dkr.ecr.us-west-2.amazonaws.com/sentiment-service:latest      

      - name: Build and Push Docker Image (dynamodb-repo)
        if: ${{ github.event.inputs.mode != 'destroy' }}
        run: |
          docker build -t dynamodb-service .
          docker tag dynamodb-service:latest 266735837076.dkr.ecr.us-west-2.amazonaws.com/dynamodb-service:latest
          docker push 266735837076.dkr.ecr.us-west-2.amazonaws.com/dynamodb-service:latest

#       - name: Terraform Init
#         run: |
#           terraform init \
#             -backend-config="bucket=terraform-state-bucket-266735837076" \
#             -backend-config="key=ec2-branch/terraform.tfstate" \
#             -backend-config="region=us-west-2" \
#             -backend-config="dynamodb_table=terraform_locks_table_ec2_branch" \
#             -backend-config="encrypt=true"

      # Step 8: Dry Run (Terraform Plan)
      - name: Terraform Plan
        if: ${{ github.event.inputs.mode == 'plan' }}
        run: terraform plan

      # Step 9: Apply Changes
      - name: Terraform Apply
        if: ${{ github.event.inputs.mode == 'apply' }}
        run: terraform apply -auto-approve

      - name: Validate Confirmation Of Destroy
        if: ${{ github.event.inputs.mode == 'destroy' }}
        run: |
          if [ "${{ github.event.inputs.confirm_destroy }}" != "delete" ]; then
            echo "Destroy confirmation not provided or incorrect. Exiting."
            exit 1
          fi
            
          echo "Confirmation provided. Proceeding to destroy step."

      # Step 10: Destroy Changes
      - name: Terraform Destroy
        if: ${{ github.event.inputs.mode == 'destroy' }}
        run: terraform destroy -auto-approve
