name: Terraform Deployment

on:
  workflow_dispatch: # Allows manual trigger of the workflow
    inputs:
      mode:
        description: 'Choose operation mode'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::266735837076:role/githubactions_aws_credentials_role
          aws-region: us-west-2

      # Step 3: Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 5: Dry Run (Terraform Plan)
      - name: Terraform Plan
        if: ${{ github.event.inputs.mode == 'plan' }}
        run: terraform plan

      # Step 6: Apply Changes
      - name: Terraform Apply
        if: ${{ github.event.inputs.mode == 'apply' }}
        run: terraform apply -auto-approve
